apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: default
type: Opaque
data:
  postgres-password: cG9zdGdyZXM=  # base64 encoded "postgres"
  app-password: YXBwX3Bhc3N3b3Jk  # base64 encoded "app_password"