server:
  port: 8080

spring:
  application:
    name: spark-operator-api

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.example.sparkoperator: DEBUG
    io.kubernetes: INFO
    org.springframework: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

spark:
  operator:
    default-namespace: default
    default-image: xinhua/spark-app:v4