server:
  port: 8080

spring:
  application:
    name: spark-operator


logging:
  level:
    com.example.sparkoperator: DEBUG
    io.kubernetes: INFO
    org.springframework: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"