kind: ConfigMap
apiVersion: v1
metadata:
  name: release-name
  labels:
    app.kubernetes.io/name: release-name
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v3.2.3"
data:
  spark-defaults.conf: |-
    spark.history.fs.eventLog.rolling.maxFilesToRetain=5
    spark.history.fs.logDirectory=/mnt/spark-history
    spark.metrics.conf=/opt/spark/conf/metrics.properties
  metrics.properties: |-
    *.sink.jmx.class=org.apache.spark.metrics.sink.JmxSink
    master.source.jvm.class=org.apache.spark.metrics.source.JvmSource
    worker.source.jvm.class=org.apache.spark.metrics.source.JvmSource
    driver.source.jvm.class=org.apache.spark.metrics.source.JvmSource
    executor.source.jvm.class=org.apache.spark.metrics.source.JvmSource