kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: spark-history-pvc
  labels:
    app.kubernetes.io/name: release-name
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v3.2.3"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem