apiVersion: v1
kind: Service
metadata:
  name: spark-history-server
spec:
  type: NodePort 
  ports:
  - port: 18080
    targetPort: 18080
    nodePort: 31000
  selector:
    app: spark-history-server